--<ScriptOptions statementTerminator=";"/>

CREATE TABLE board (
	num INT NOT NULL,
	writer VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	subject VARCHAR(100) NOT NULL,
	userPassword VARCHAR(20) NOT NULL,
	readcount INT DEFAULT 0,
	ref INT DEFAULT 0,
	step INT DEFAULT 0,
	depth INT DEFAULT 0,
	regdate TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP',
	content VARCHAR(1000) NOT NULL,
	PRIMARY KEY (num)
);

CREATE TABLE user (
	userID VARCHAR(20) NOT NULL,
	userPassword VARCHAR(20),
	userEmail VARCHAR(50),
	userName VARCHAR(20),
	userJumin VARCHAR(20),
	userAlchol VARCHAR(20),
	Host CHAR(255) NOT NULL,
	User CHAR(32) NOT NULL,
	Select_priv ENUM DEFAULT N NOT NULL,
	Insert_priv ENUM DEFAULT N NOT NULL,
	Update_priv ENUM DEFAULT N NOT NULL,
	Delete_priv ENUM DEFAULT N NOT NULL,
	Create_priv ENUM DEFAULT N NOT NULL,
	Drop_priv ENUM DEFAULT N NOT NULL,
	Reload_priv ENUM DEFAULT N NOT NULL,
	Shutdown_priv ENUM DEFAULT N NOT NULL,
	Process_priv ENUM DEFAULT N NOT NULL,
	File_priv ENUM DEFAULT N NOT NULL,
	Grant_priv ENUM DEFAULT N NOT NULL,
	References_priv ENUM DEFAULT N NOT NULL,
	Index_priv ENUM DEFAULT N NOT NULL,
	Alter_priv ENUM DEFAULT N NOT NULL,
	Show_db_priv ENUM DEFAULT N NOT NULL,
	Super_priv ENUM DEFAULT N NOT NULL,
	Create_tmp_table_priv ENUM DEFAULT N NOT NULL,
	Lock_tables_priv ENUM DEFAULT N NOT NULL,
	Execute_priv ENUM DEFAULT N NOT NULL,
	Repl_slave_priv ENUM DEFAULT N NOT NULL,
	Repl_client_priv ENUM DEFAULT N NOT NULL,
	Create_view_priv ENUM DEFAULT N NOT NULL,
	Show_view_priv ENUM DEFAULT N NOT NULL,
	Create_routine_priv ENUM DEFAULT N NOT NULL,
	Alter_routine_priv ENUM DEFAULT N NOT NULL,
	Create_user_priv ENUM DEFAULT N NOT NULL,
	Event_priv ENUM DEFAULT N NOT NULL,
	Trigger_priv ENUM DEFAULT N NOT NULL,
	Create_tablespace_priv ENUM DEFAULT N NOT NULL,
	ssl_type ENUM NOT NULL,
	ssl_cipher BLOB NOT NULL,
	x509_issuer BLOB NOT NULL,
	x509_subject BLOB NOT NULL,
	max_questions INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	max_updates INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	max_connections INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	max_user_connections INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	plugin CHAR(64) DEFAULT caching_sha2_password NOT NULL,
	authentication_string TEXT,
	password_expired ENUM DEFAULT N NOT NULL,
	password_last_changed TIMESTAMP,
	password_lifetime SMALLINT UNSIGNED,
	account_locked ENUM DEFAULT N NOT NULL,
	Create_role_priv ENUM DEFAULT N NOT NULL,
	Drop_role_priv ENUM DEFAULT N NOT NULL,
	Password_reuse_history SMALLINT UNSIGNED,
	Password_reuse_time SMALLINT UNSIGNED,
	Password_require_current ENUM,
	User_attributes null,
	PRIMARY KEY (Host,User)
);

